# Syntax highlighting
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Setup
title: "@rey"
tagline: Suffering at my own will
url: "exkcd.github.io"
baseurl: ""

# Permalinks
permalink: pretty

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Directory navigation
nav:
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
  - title: Writing
    url: /archive


# For my photography photos
include:
  - "_img"

# Exclusions
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
