# Syntax highlighting
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Setup
# When making this a subdomain, refer to past past jekyll versions please
title: "@rey"
tagline: Suffering at my own will
url: "https://exkcd.github.io/blog"

# Permalinks
permalink: pretty

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Directory navigation
nav:
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
  - title: Writing
    url: /archive

# Tag plugin
tag_page_layout: tagpage
tag_page_dir: tag
tag_permalink_style: pretty
# ignored_tags: (if I want any tags to not be included in the indexing)

# For my photography photos
include:
  - "_img"

# Exclusions
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
